export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_SUCCESSFULL = 'LOGIN_SUCCESSFULL';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_START = 'LOGIN_START';

export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE';
export const EMPLOYEE_ADDED = 'EMPLOYEE_ADDED';
export const FETCH_EMPLOYEESS_SUCCESS = 'FETCH_EMPLOYEESS_SUCCESS';
export const FETCH_EMPLOYEESS_STARTED = 'FETCH_EMPLOYEESS_STARTED';
